PRODUCT_COPY_FILES += \
    vendor/xiaomi/hermes/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/xiaomi/hermes/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/xiaomi/hermes/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/xiaomi/hermes/proprietary/bin/aal:system/bin/aal \
    vendor/xiaomi/hermes/proprietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
    vendor/xiaomi/hermes/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/xiaomi/hermes/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/xiaomi/hermes/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/xiaomi/hermes/proprietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/xiaomi/hermes/proprietary/bin/autokd:system/bin/autokd \
    vendor/xiaomi/hermes/proprietary/bin/badblocks:system/bin/badblocks \
    vendor/xiaomi/hermes/proprietary/bin/bmi160d:system/bin/bmi160d \
    vendor/xiaomi/hermes/proprietary/bin/bmm050d:system/bin/bmm050d \
    vendor/xiaomi/hermes/proprietary/bin/btconfig:system/bin/btconfig \
    vendor/xiaomi/hermes/proprietary/bin/btlogmask:system/bin/btlogmask \
    vendor/xiaomi/hermes/proprietary/bin/capture_audio.sh:system/bin/capture_audio.sh \
    vendor/xiaomi/hermes/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/xiaomi/hermes/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/xiaomi/hermes/proprietary/bin/consumerird:system/bin/consumerird \
    vendor/xiaomi/hermes/proprietary/bin/dhcp6c:system/bin/dhcp6c \
    vendor/xiaomi/hermes/proprietary/bin/dhcp6ctl:system/bin/dhcp6ctl \
    vendor/xiaomi/hermes/proprietary/bin/dhcp6s:system/bin/dhcp6s \
    vendor/xiaomi/hermes/proprietary/bin/evi:system/bin/evi \
    vendor/xiaomi/hermes/proprietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/xiaomi/hermes/proprietary/bin/fuelgauged:system/bin/fuelgauged \
    vendor/xiaomi/hermes/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/xiaomi/hermes/proprietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
    vendor/xiaomi/hermes/proprietary/bin/gsm0710muxdmd2:system/bin/gsm0710muxdmd2 \
    vendor/xiaomi/hermes/proprietary/bin/guiext-server:system/bin/guiext-server \
    vendor/xiaomi/hermes/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/xiaomi/hermes/proprietary/bin/hostapd_cli:system/bin/hostapd_cli \
    vendor/xiaomi/hermes/proprietary/bin/init.atmel_ts.sh:system/bin/init.atmel_ts.sh \
    vendor/xiaomi/hermes/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/xiaomi/hermes/proprietary/bin/lcdc_screen_cap:system/bin/lcdc_screen_cap \
    vendor/xiaomi/hermes/proprietary/bin/lsm303md:system/bin/lsm303md \
    vendor/xiaomi/hermes/proprietary/bin/magd:system/bin/magd \
    vendor/xiaomi/hermes/proprietary/bin/make_ext4fs:system/bin/make_ext4fs \
    vendor/xiaomi/hermes/proprietary/bin/matv:system/bin/matv \
    vendor/xiaomi/hermes/proprietary/bin/mc6420d:system/bin/mc6420d \
    vendor/xiaomi/hermes/proprietary/bin/mcd:system/bin/mcd \
    vendor/xiaomi/hermes/proprietary/bin/md_ctrl:system/bin/md_ctrl \
    vendor/xiaomi/hermes/proprietary/bin/memorydumper:system/bin/memorydumper \
    vendor/xiaomi/hermes/proprietary/bin/memsicd:system/bin/memsicd \
    vendor/xiaomi/hermes/proprietary/bin/memsicd3416x:system/bin/memsicd3416x \
    vendor/xiaomi/hermes/proprietary/bin/meta_tst:system/bin/meta_tst \
    vendor/xiaomi/hermes/proprietary/bin/mfv_ut:system/bin/mfv_ut \
    vendor/xiaomi/hermes/proprietary/bin/mmp:system/bin/mmp \
    vendor/xiaomi/hermes/proprietary/bin/mpud6050:system/bin/mpud6050 \
    vendor/xiaomi/hermes/proprietary/bin/msensord:system/bin/msensord \
    vendor/xiaomi/hermes/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/xiaomi/hermes/proprietary/bin/mtk_setprop:system/bin/mtk_setprop \
    vendor/xiaomi/hermes/proprietary/bin/mtkbt:system/bin/mtkbt \
    vendor/xiaomi/hermes/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/xiaomi/hermes/proprietary/bin/mtkrild:system/bin/mtkrild \
    vendor/xiaomi/hermes/proprietary/bin/mtkrildmd2:system/bin/mtkrildmd2 \
    vendor/xiaomi/hermes/proprietary/bin/netcfg:system/bin/netcfg \
    vendor/xiaomi/hermes/proprietary/bin/netdiag:system/bin/netdiag \
    vendor/xiaomi/hermes/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/xiaomi/hermes/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/xiaomi/hermes/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/xiaomi/hermes/proprietary/bin/perf_native_test:system/bin/perf_native_test \
    vendor/xiaomi/hermes/proprietary/bin/permission_check:system/bin/permission_check \
    vendor/xiaomi/hermes/proprietary/bin/playback_audio.sh:system/bin/playback_audio.sh \
    vendor/xiaomi/hermes/proprietary/bin/ppl_agent:system/bin/ppl_agent \
    vendor/xiaomi/hermes/proprietary/bin/pppd:system/bin/pppd \
    vendor/xiaomi/hermes/proprietary/bin/pppd_btdun:system/bin/pppd_btdun \
    vendor/xiaomi/hermes/proprietary/bin/pppd_dt:system/bin/pppd_dt \
    vendor/xiaomi/hermes/proprietary/bin/pq:system/bin/pq \
    vendor/xiaomi/hermes/proprietary/bin/racoon:system/bin/racoon \
    vendor/xiaomi/hermes/proprietary/bin/radvd:system/bin/radvd \
    vendor/xiaomi/hermes/proprietary/bin/rtt:system/bin/rtt \
    vendor/xiaomi/hermes/proprietary/bin/run-as:system/bin/run-as \
    vendor/xiaomi/hermes/proprietary/bin/s62xd:system/bin/s62xd \
    vendor/xiaomi/hermes/proprietary/bin/screencolor:system/bin/screencolor \
    vendor/xiaomi/hermes/proprietary/bin/stp_dump3:system/bin/stp_dump3 \
    vendor/xiaomi/hermes/proprietary/bin/thermal:system/bin/thermal \
    vendor/xiaomi/hermes/proprietary/bin/thermal_manager:system/bin/thermal_manager \
    vendor/xiaomi/hermes/proprietary/bin/thermald:system/bin/thermald \
    vendor/xiaomi/hermes/proprietary/bin/tiny_mkswap:system/bin/tiny_mkswap \
    vendor/xiaomi/hermes/proprietary/bin/tiny_swapoff:system/bin/tiny_swapoff \
    vendor/xiaomi/hermes/proprietary/bin/tiny_swapon:system/bin/tiny_swapon \
    vendor/xiaomi/hermes/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/xiaomi/hermes/proprietary/bin/xlog:system/bin/xlog \
    vendor/xiaomi/hermes/proprietary/bin/yamaha537:system/bin/yamaha537 \
    vendor/xiaomi/hermes/proprietary/etc/bluetooth/auto_pair_blacklist.conf:system/etc/bluetooth/auto_pair_blacklist.conf \
    vendor/xiaomi/hermes/proprietary/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
    vendor/xiaomi/hermes/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/xiaomi/hermes/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/xiaomi/hermes/proprietary/etc/bluetooth/btconfig.xml:system/etc/bluetooth/btconfig.xml \
    vendor/xiaomi/hermes/proprietary/etc/clatd.conf:system/etc/clatd.conf \
    vendor/xiaomi/hermes/proprietary/etc/custom.conf:system/etc/custom.conf \
    vendor/xiaomi/hermes/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    vendor/xiaomi/hermes/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:system/etc/dhcpcd/dhcpcd-hooks/95-configured \
    vendor/xiaomi/hermes/proprietary/etc/dhcpcd/dhcpcd-run-hooks:system/etc/dhcpcd/dhcpcd-run-hooks \
    vendor/xiaomi/hermes/proprietary/etc/firmware/A4_15_2.2_AA.fw:system/etc/firmware/A4_15_2.2_AA.fw \
    vendor/xiaomi/hermes/proprietary/etc/firmware/A4_15_2.2_AA.raw:system/etc/firmware/A4_15_2.2_AA.raw \
    vendor/xiaomi/hermes/proprietary/etc/firmware/catcher_filter_1_ltg_n.bin:system/etc/firmware/catcher_filter_1_ltg_n.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/catcher_filter_1_lwg_n.bin:system/etc/firmware/catcher_filter_1_lwg_n.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/dsp_1_ltg_n.bin:system/etc/firmware/dsp_1_ltg_n.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/dsp_1_lwg_n.bin:system/etc/firmware/dsp_1_lwg_n.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/md32_d.bin:system/etc/firmware/md32_d.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/md32_p.bin:system/etc/firmware/md32_p.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/modem_1_ltg_n.img:system/etc/firmware/modem_1_ltg_n.img \
    vendor/xiaomi/hermes/proprietary/etc/firmware/modem_1_lwg_n.img:system/etc/firmware/modem_1_lwg_n.img \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v1_coeff.bin:system/etc/firmware/mt6630/mt6630_fm_v1_coeff.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v1_coeff_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v1_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v1_patch.bin:system/etc/firmware/mt6630/mt6630_fm_v1_patch.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v1_patch_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v1_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v2_coeff.bin:system/etc/firmware/mt6630/mt6630_fm_v2_coeff.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v2_coeff_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v2_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v2_patch.bin:system/etc/firmware/mt6630/mt6630_fm_v2_patch.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v2_patch_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v2_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v3_coeff.bin:system/etc/firmware/mt6630/mt6630_fm_v3_coeff.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v3_coeff_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v3_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v3_patch.bin:system/etc/firmware/mt6630/mt6630_fm_v3_patch.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v3_patch_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v3_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v4_coeff.bin:system/etc/firmware/mt6630/mt6630_fm_v4_coeff.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v4_coeff_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v4_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v4_patch.bin:system/etc/firmware/mt6630/mt6630_fm_v4_patch.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v4_patch_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v4_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v5_coeff.bin:system/etc/firmware/mt6630/mt6630_fm_v5_coeff.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v5_coeff_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v5_coeff_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v5_patch.bin:system/etc/firmware/mt6630/mt6630_fm_v5_patch.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630/mt6630_fm_v5_patch_tx.bin:system/etc/firmware/mt6630/mt6630_fm_v5_patch_tx.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630_ant_m1.cfg:system/etc/firmware/mt6630_ant_m1.cfg \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630_patch_e1_hdr.bin:system/etc/firmware/mt6630_patch_e1_hdr.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630_patch_e2_hdr.bin:system/etc/firmware/mt6630_patch_e2_hdr.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630_patch_e3_0_hdr.bin:system/etc/firmware/mt6630_patch_e3_0_hdr.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/mt6630_patch_e3_1_hdr.bin:system/etc/firmware/mt6630_patch_e3_1_hdr.bin \
    vendor/xiaomi/hermes/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:system/etc/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/xiaomi/hermes/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
    vendor/xiaomi/hermes/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/xiaomi/hermes/proprietary/etc/mddb/BPLGUInfoCustomAppSrcP_MT6795_S00_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_1_ltg_n:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6795_S00_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_1_ltg_n \
    vendor/xiaomi/hermes/proprietary/etc/mddb/BPLGUInfoCustomAppSrcP_MT6795_S00_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_1_lwg_n:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6795_S00_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_1_lwg_n \
    vendor/xiaomi/hermes/proprietary/etc/mddb/DbgInfo_LR9.W1423.MD.LWTG.MP_LCSH6795_LWT_L_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_2016_01_19_19_22_1_ltg_n:system/etc/mddb/DbgInfo_LR9.W1423.MD.LWTG.MP_LCSH6795_LWT_L_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_2016_01_19_19_22_1_ltg_n \
    vendor/xiaomi/hermes/proprietary/etc/mddb/DbgInfo_LR9.W1423.MD.LWTG.MP_LCSH6795_LWT_L_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_2016_01_19_19_24_1_lwg_n:system/etc/mddb/DbgInfo_LR9.W1423.MD.LWTG.MP_LCSH6795_LWT_L_MOLY_LR9_W1423_MD_LWTG_MP_V24_P51_2016_01_19_19_24_1_lwg_n \
    vendor/xiaomi/hermes/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/xiaomi/hermes/proprietary/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    vendor/xiaomi/hermes/proprietary/etc/radvd/radvd.conf:system/etc/radvd/radvd.conf \
    vendor/xiaomi/hermes/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/xiaomi/hermes/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/xiaomi/hermes/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/xiaomi/hermes/proprietary/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so \
    vendor/xiaomi/hermes/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/xiaomi/hermes/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/audio.primary.mt6795.so:system/lib/hw/audio.primary.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/camera.mt6795.so:system/lib/hw/camera.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/consumerir.default.so:system/lib/hw/consumerir.default.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/hwcomposer.mt6795.so:system/lib/hw/hwcomposer.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/memtrack.mt6795.so:system/lib/hw/memtrack.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/mmsdk.default.so:system/lib/hw/mmsdk.default.so \
    vendor/xiaomi/hermes/proprietary/lib/hw/sensors.mt6795.so:system/lib/hw/sensors.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/xiaomi/hermes/proprietary/lib/lib3a_sample.so:system/lib/lib3a_sample.so \
    vendor/xiaomi/hermes/proprietary/lib/liba3m.so:system/lib/liba3m.so \
    vendor/xiaomi/hermes/proprietary/lib/libaal.so:system/lib/libaal.so \
    vendor/xiaomi/hermes/proprietary/lib/libaal_cust.so:system/lib/libaal_cust.so \
    vendor/xiaomi/hermes/proprietary/lib/libacdk.so:system/lib/libacdk.so \
    vendor/xiaomi/hermes/proprietary/lib/libadpcm.so:system/lib/libadpcm.so \
    vendor/xiaomi/hermes/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/xiaomi/hermes/proprietary/lib/libAGifEncoder.so:system/lib/libAGifEncoder.so \
    vendor/xiaomi/hermes/proprietary/lib/libatciserv_jni.so:system/lib/libatciserv_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libatvctrlservice.so:system/lib/libatvctrlservice.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/xiaomi/hermes/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/xiaomi/hermes/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/xiaomi/hermes/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/xiaomi/hermes/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/xiaomi/hermes/proprietary/lib/libbluetoothdrv.so:system/lib/libbluetoothdrv.so \
    vendor/xiaomi/hermes/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtcust.so:system/lib/libbtcust.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtcusttable.so:system/lib/libbtcusttable.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtcusttc1.so:system/lib/libbtcusttc1.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtem.so:system/lib/libbtem.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtpcm.so:system/lib/libbtpcm.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtsession.so:system/lib/libbtsession.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtsniff.so:system/lib/libbtsniff.so \
    vendor/xiaomi/hermes/proprietary/lib/libbtstd.so:system/lib/libbtstd.so \
    vendor/xiaomi/hermes/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.camnode.so:system/lib/libcam.camnode.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.faceagegender.so:system/lib/libcam.faceagegender.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.jni.lomohaljni.so:system/lib/libcam.jni.lomohaljni.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam.watermark.so:system/lib/libcam.watermark.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/xiaomi/hermes/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/xiaomi/hermes/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/xiaomi/hermes/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/xiaomi/hermes/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/xiaomi/hermes/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/xiaomi/hermes/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/xiaomi/hermes/proprietary/lib/libCameraEffectJNI.so:system/lib/libCameraEffectJNI.so \
    vendor/xiaomi/hermes/proprietary/lib/libccci_util.so:system/lib/libccci_util.so \
    vendor/xiaomi/hermes/proprietary/lib/libClearMotionFW.so:system/lib/libClearMotionFW.so \
    vendor/xiaomi/hermes/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/xiaomi/hermes/proprietary/lib/libcustom_jni.so:system/lib/libcustom_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/xiaomi/hermes/proprietary/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    vendor/xiaomi/hermes/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libdcfdecoderjni.so:system/lib/libdcfdecoderjni.so \
    vendor/xiaomi/hermes/proprietary/lib/libDiracAPI_SHARED.so:system/lib/libDiracAPI_SHARED.so \
    vendor/xiaomi/hermes/proprietary/lib/libdirect-coredump.so:system/lib/libdirect-coredump.so \
    vendor/xiaomi/hermes/proprietary/lib/libdngop.so:system/lib/libdngop.so \
    vendor/xiaomi/hermes/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/xiaomi/hermes/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/xiaomi/hermes/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/xiaomi/hermes/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    vendor/xiaomi/hermes/proprietary/lib/libextsys.so:system/lib/libextsys.so \
    vendor/xiaomi/hermes/proprietary/lib/libextsys_jni.so:system/lib/libextsys_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libexttestmode.so:system/lib/libexttestmode.so \
    vendor/xiaomi/hermes/proprietary/lib/libFaceProc.so:system/lib/libFaceProc.so \
    vendor/xiaomi/hermes/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/xiaomi/hermes/proprietary/lib/libfgauge.so:system/lib/libfgauge.so \
    vendor/xiaomi/hermes/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/xiaomi/hermes/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmjni.so:system/lib/libfmjni.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmmt6620.so:system/lib/libfmmt6620.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmmt6627.so:system/lib/libfmmt6627.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmmt6628.so:system/lib/libfmmt6628.so \
    vendor/xiaomi/hermes/proprietary/lib/libfmmt6630.so:system/lib/libfmmt6630.so \
    vendor/xiaomi/hermes/proprietary/lib/libGdmaScalerPipe.so:system/lib/libGdmaScalerPipe.so \
    vendor/xiaomi/hermes/proprietary/lib/libged.so:system/lib/libged.so \
    vendor/xiaomi/hermes/proprietary/lib/libgifEncoder_jni.so:system/lib/libgifEncoder_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libgpu_aux.so:system/lib/libgpu_aux.so \
    vendor/xiaomi/hermes/proprietary/lib/libgraphite2.so:system/lib/libgraphite2.so \
    vendor/xiaomi/hermes/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/xiaomi/hermes/proprietary/lib/libh264enc_sa.ca7.so:system/lib/libh264enc_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libHEVCdec_sa.ca7.android.so:system/lib/libHEVCdec_sa.ca7.android.so \
    vendor/xiaomi/hermes/proprietary/lib/libhotknot.so:system/lib/libhotknot.so \
    vendor/xiaomi/hermes/proprietary/lib/libhotknot_vendor.so:system/lib/libhotknot_vendor.so \
    vendor/xiaomi/hermes/proprietary/lib/libhttpserver.so:system/lib/libhttpserver.so \
    vendor/xiaomi/hermes/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/xiaomi/hermes/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/xiaomi/hermes/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/xiaomi/hermes/proprietary/lib/libImageSearchAPI.so:system/lib/libImageSearchAPI.so \
    vendor/xiaomi/hermes/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/xiaomi/hermes/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libja3m.so:system/lib/libja3m.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_effects.so:system/lib/libjni_effects.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_gesture.so:system/lib/libjni_gesture.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_imagetransform.so:system/lib/libjni_imagetransform.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_lomoeffect.so:system/lib/libjni_lomoeffect.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_mosaic_old.so:system/lib/libjni_mosaic_old.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_pq.so:system/lib/libjni_pq.so \
    vendor/xiaomi/hermes/proprietary/lib/libjni_resource_drm.so:system/lib/libjni_resource_drm.so \
    vendor/xiaomi/hermes/proprietary/lib/libJniAtvService.so:system/lib/libJniAtvService.so \
    vendor/xiaomi/hermes/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/xiaomi/hermes/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/xiaomi/hermes/proprietary/lib/libjtranscode.so:system/lib/libjtranscode.so \
    vendor/xiaomi/hermes/proprietary/lib/liblogwrap.so:system/lib/liblogwrap.so \
    vendor/xiaomi/hermes/proprietary/lib/libm.so:system/lib/libm.so \
    vendor/xiaomi/hermes/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/xiaomi/hermes/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/xiaomi/hermes/proprietary/lib/libmdloggerrecycle.so:system/lib/libmdloggerrecycle.so \
    vendor/xiaomi/hermes/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
    vendor/xiaomi/hermes/proprietary/lib/libmemoryDumpEncoder.so:system/lib/libmemoryDumpEncoder.so \
    vendor/xiaomi/hermes/proprietary/lib/libmemorydumper.so:system/lib/libmemorydumper.so \
    vendor/xiaomi/hermes/proprietary/lib/libmemtrack_GL.so:system/lib/libmemtrack_GL.so \
    vendor/xiaomi/hermes/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/xiaomi/hermes/proprietary/lib/libmjc.so:system/lib/libmjc.so \
    vendor/xiaomi/hermes/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/xiaomi/hermes/proprietary/lib/libmmprofile_jni.so:system/lib/libmmprofile_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
    vendor/xiaomi/hermes/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/xiaomi/hermes/proprietary/lib/libmp3lame.so:system/lib/libmp3lame.so \
    vendor/xiaomi/hermes/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/xiaomi/hermes/proprietary/lib/libmpodecoder.so:system/lib/libmpodecoder.so \
    vendor/xiaomi/hermes/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/xiaomi/hermes/proprietary/lib/libmpojni.so:system/lib/libmpojni.so \
    vendor/xiaomi/hermes/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtb.so:system/lib/libmtb.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtkbtextspp.so:system/lib/libmtkbtextspp.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/xiaomi/hermes/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkVideoSpeedEffect.so:system/lib/libMtkVideoSpeedEffect.so \
    vendor/xiaomi/hermes/proprietary/lib/libMtkVideoTranscoder.so:system/lib/libMtkVideoTranscoder.so \
    vendor/xiaomi/hermes/proprietary/lib/libn3d3a.so:system/lib/libn3d3a.so \
    vendor/xiaomi/hermes/proprietary/lib/libnativecheck-jni.so:system/lib/libnativecheck-jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \
    vendor/xiaomi/hermes/proprietary/lib/libnfc_ndef.so:system/lib/libnfc_ndef.so \
    vendor/xiaomi/hermes/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/xiaomi/hermes/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/xiaomi/hermes/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/xiaomi/hermes/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/xiaomi/hermes/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/xiaomi/hermes/proprietary/lib/libpalsecurity.so:system/lib/libpalsecurity.so \
    vendor/xiaomi/hermes/proprietary/lib/libpalwlan_mtk.so:system/lib/libpalwlan_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib/libperfservice.so:system/lib/libperfservice.so \
    vendor/xiaomi/hermes/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/xiaomi/hermes/proprietary/lib/libpppbtdun.so:system/lib/libpppbtdun.so \
    vendor/xiaomi/hermes/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/xiaomi/hermes/proprietary/lib/libpq_prot.so:system/lib/libpq_prot.so \
    vendor/xiaomi/hermes/proprietary/lib/libPQDCjni.so:system/lib/libPQDCjni.so \
    vendor/xiaomi/hermes/proprietary/lib/libPQjni.so:system/lib/libPQjni.so \
    vendor/xiaomi/hermes/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/xiaomi/hermes/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
    vendor/xiaomi/hermes/proprietary/lib/libsbccodec.so:system/lib/libsbccodec.so \
    vendor/xiaomi/hermes/proprietary/lib/libsec.so:system/lib/libsec.so \
    vendor/xiaomi/hermes/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/xiaomi/hermes/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/xiaomi/hermes/proprietary/lib/libssladp.so:system/lib/libssladp.so \
    vendor/xiaomi/hermes/proprietary/lib/libstagefright_memutil.so:system/lib/libstagefright_memutil.so \
    vendor/xiaomi/hermes/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/xiaomi/hermes/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/xiaomi/hermes/proprietary/lib/libtimestretch.so:system/lib/libtimestretch.so \
    vendor/xiaomi/hermes/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/xiaomi/hermes/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/xiaomi/hermes/proprietary/lib/libtouchfilter.so:system/lib/libtouchfilter.so \
    vendor/xiaomi/hermes/proprietary/lib/libudf.so:system/lib/libudf.so \
    vendor/xiaomi/hermes/proprietary/lib/libui.so:system/lib/libui.so \
    vendor/xiaomi/hermes/proprietary/lib/libui_ext.so:system/lib/libui_ext.so \
    vendor/xiaomi/hermes/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/xiaomi/hermes/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/xiaomi/hermes/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/xiaomi/hermes/proprietary/lib/libvie.so:system/lib/libvie.so \
    vendor/xiaomi/hermes/proprietary/lib/libvie_jni.so:system/lib/libvie_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libvoicerecognition.so:system/lib/libvoicerecognition.so \
    vendor/xiaomi/hermes/proprietary/lib/libvoicerecognition_jni.so:system/lib/libvoicerecognition_jni.so \
    vendor/xiaomi/hermes/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/xiaomi/hermes/proprietary/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
    vendor/xiaomi/hermes/proprietary/lib/libwebviewchromium_loader.so:system/lib/libwebviewchromium_loader.so \
    vendor/xiaomi/hermes/proprietary/lib/libwebviewchromium_plat_support.so:system/lib/libwebviewchromium_plat_support.so \
    vendor/xiaomi/hermes/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/xiaomi/hermes/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
    vendor/xiaomi/hermes/proprietary/lib/soundfx/libdirac.so:system/lib/soundfx/libdirac.so \
    vendor/xiaomi/hermes/proprietary/lib64/egl/libGLES_android.so:system/lib64/egl/libGLES_android.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/audio.primary.mt6795.so:system/lib64/hw/audio.primary.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/camera.mt6795.so:system/lib64/hw/camera.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/consumerir.default.so:system/lib64/hw/consumerir.default.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/hwcomposer.mt6795.so:system/lib64/hw/hwcomposer.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/lights.default.so:system/lib64/hw/lights.default.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/memtrack.mt6795.so:system/lib64/hw/memtrack.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/mmsdk.default.so:system/lib64/hw/mmsdk.default.so \
    vendor/xiaomi/hermes/proprietary/lib64/hw/sensors.mt6795.so:system/lib64/hw/sensors.mt6795.so \
    vendor/xiaomi/hermes/proprietary/lib64/lib3a.so:system/lib64/lib3a.so \
    vendor/xiaomi/hermes/proprietary/lib64/lib3a_sample.so:system/lib64/lib3a_sample.so \
    vendor/xiaomi/hermes/proprietary/lib64/lib_unique_id.so:system/lib64/lib_unique_id.so \
    vendor/xiaomi/hermes/proprietary/lib64/liba3m.so:system/lib64/liba3m.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaal.so:system/lib64/libaal.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaal_cust.so:system/lib64/libaal_cust.so \
    vendor/xiaomi/hermes/proprietary/lib64/libacdk.so:system/lib64/libacdk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaed.so:system/lib64/libaed.so \
    vendor/xiaomi/hermes/proprietary/lib64/libatciserv_jni.so:system/lib64/libatciserv_jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libatvctrlservice.so:system/lib64/libatvctrlservice.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiocompensationfilter.so:system/lib64/libaudiocompensationfilter.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiocomponentengine.so:system/lib64/libaudiocomponentengine.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiocustparam.so:system/lib64/libaudiocustparam.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiodcrflt.so:system/lib64/libaudiodcrflt.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiopolicymanager.so:system/lib64/libaudiopolicymanager.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiopolicymanagerdefault.so:system/lib64/libaudiopolicymanagerdefault.so \
    vendor/xiaomi/hermes/proprietary/lib64/libaudiosetting.so:system/lib64/libaudiosetting.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbessound_hd_mtk.so:system/lib64/libbessound_hd_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libblisrc.so:system/lib64/libblisrc.so \
    vendor/xiaomi/hermes/proprietary/lib64/libblisrc32.so:system/lib64/libblisrc32.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbluetooth_relayer.so:system/lib64/libbluetooth_relayer.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbluetoothdrv.so:system/lib64/libbluetoothdrv.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbluetoothem_mtk.so:system/lib64/libbluetoothem_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbtcusttable.so:system/lib64/libbtcusttable.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbtem.so:system/lib64/libbtem.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbtstd.so:system/lib64/libbtstd.so \
    vendor/xiaomi/hermes/proprietary/lib64/libbwc.so:system/lib64/libbwc.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.camnode.so:system/lib64/libcam.camnode.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.client.so:system/lib64/libcam.client.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.faceagegender.so:system/lib64/libcam.faceagegender.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.jni.lomohaljni.so:system/lib64/libcam.jni.lomohaljni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.sdkclient.so:system/lib64/libcam.sdkclient.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam.watermark.so:system/lib64/libcam.watermark.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcamera_client.so:system/lib64/libcamera_client.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcamera_client_mtk.so:system/lib64/libcamera_client_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcamera_metadata.so:system/lib64/libcamera_metadata.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    vendor/xiaomi/hermes/proprietary/lib64/libCameraEffectJNI.so:system/lib64/libCameraEffectJNI.so \
    vendor/xiaomi/hermes/proprietary/lib64/libccci_util.so:system/lib64/libccci_util.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcurl.so:system/lib64/libcurl.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcustom_jni.so:system/lib64/libcustom_jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcustom_prop.so:system/lib64/libcustom_prop.so \
    vendor/xiaomi/hermes/proprietary/lib64/libcvsd_mtk.so:system/lib64/libcvsd_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdcfdecoderjni.so:system/lib64/libdcfdecoderjni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdirect-coredump.so:system/lib64/libdirect-coredump.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdngop.so:system/lib64/libdngop.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdpframework.so:system/lib64/libdpframework.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdrmmtkutil.so:system/lib64/libdrmmtkutil.so \
    vendor/xiaomi/hermes/proprietary/lib64/libdrmmtkwhitelist.so:system/lib64/libdrmmtkwhitelist.so \
    vendor/xiaomi/hermes/proprietary/lib64/libextadvanced_jni.so:system/lib64/libextadvanced_jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libextem.so:system/lib64/libextem.so \
    vendor/xiaomi/hermes/proprietary/lib64/libextsys.so:system/lib64/libextsys.so \
    vendor/xiaomi/hermes/proprietary/lib64/libextsys_jni.so:system/lib64/libextsys_jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libFaceProc.so:system/lib64/libFaceProc.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfile_op.so:system/lib64/libfile_op.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmcust.so:system/lib64/libfmcust.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmjni.so:system/lib64/libfmjni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmmt6620.so:system/lib64/libfmmt6620.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmmt6627.so:system/lib64/libfmmt6627.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmmt6628.so:system/lib64/libfmmt6628.so \
    vendor/xiaomi/hermes/proprietary/lib64/libfmmt6630.so:system/lib64/libfmmt6630.so \
    vendor/xiaomi/hermes/proprietary/lib64/libGdmaScalerPipe.so:system/lib64/libGdmaScalerPipe.so \
    vendor/xiaomi/hermes/proprietary/lib64/libged.so:system/lib64/libged.so \
    vendor/xiaomi/hermes/proprietary/lib64/libgpu_aux.so:system/lib64/libgpu_aux.so \
    vendor/xiaomi/hermes/proprietary/lib64/libgraphite2.so:system/lib64/libgraphite2.so \
    vendor/xiaomi/hermes/proprietary/lib64/libgui_ext.so:system/lib64/libgui_ext.so \
    vendor/xiaomi/hermes/proprietary/lib64/libhotknot.so:system/lib64/libhotknot.so \
    vendor/xiaomi/hermes/proprietary/lib64/libhotknot_vendor.so:system/lib64/libhotknot_vendor.so \
    vendor/xiaomi/hermes/proprietary/lib64/libhttpserver.so:system/lib64/libhttpserver.so \
    vendor/xiaomi/hermes/proprietary/lib64/libhwm.so:system/lib64/libhwm.so \
    vendor/xiaomi/hermes/proprietary/lib64/libimageio.so:system/lib64/libimageio.so \
    vendor/xiaomi/hermes/proprietary/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    vendor/xiaomi/hermes/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/xiaomi/hermes/proprietary/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libja3m.so:system/lib64/libja3m.so \
    vendor/xiaomi/hermes/proprietary/lib64/libjni_lomoeffect.so:system/lib64/libjni_lomoeffect.so \
    vendor/xiaomi/hermes/proprietary/lib64/libjni_mosaic_old.so:system/lib64/libjni_mosaic_old.so \
    vendor/xiaomi/hermes/proprietary/lib64/libjni_pq.so:system/lib64/libjni_pq.so \
    vendor/xiaomi/hermes/proprietary/lib64/libjni_resource_drm.so:system/lib64/libjni_resource_drm.so \
    vendor/xiaomi/hermes/proprietary/lib64/libJpgDecPipe.so:system/lib64/libJpgDecPipe.so \
    vendor/xiaomi/hermes/proprietary/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    vendor/xiaomi/hermes/proprietary/lib64/liblogwrap.so:system/lib64/liblogwrap.so \
    vendor/xiaomi/hermes/proprietary/lib64/libm4u.so:system/lib64/libm4u.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmdloggerrecycle.so:system/lib64/libmdloggerrecycle.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmediatek_exceptionlog.so:system/lib64/libmediatek_exceptionlog.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmemoryDumpEncoder.so:system/lib64/libmemoryDumpEncoder.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmemorydumper.so:system/lib64/libmemorydumper.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmemtrack_GL.so:system/lib64/libmemtrack_GL.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmhalImageCodec.so:system/lib64/libmhalImageCodec.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmmprofile_jni.so:system/lib64/libmmprofile_jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmmsdkservice.so:system/lib64/libmmsdkservice.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmp3lame.so:system/lib64/libmp3lame.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmpo.so:system/lib64/libmpo.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmpoencoder.so:system/lib64/libmpoencoder.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmsbc_mtk.so:system/lib64/libmsbc_mtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/xiaomi/hermes/proprietary/lib64/libMtkOmxCore.so:system/lib64/libMtkOmxCore.so \
    vendor/xiaomi/hermes/proprietary/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    vendor/xiaomi/hermes/proprietary/lib64/libMtkVideoTranscoder.so:system/lib64/libMtkVideoTranscoder.so \
    vendor/xiaomi/hermes/proprietary/lib64/libn3d3a.so:system/lib64/libn3d3a.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnativecheck-jni.so:system/lib64/libnativecheck-jni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnetutils.so:system/lib64/libnetutils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnfc_ndef.so:system/lib64/libnfc_ndef.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnvram.so:system/lib64/libnvram.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnvram_daemon_callback.so:system/lib64/libnvram_daemon_callback.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
    vendor/xiaomi/hermes/proprietary/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
    vendor/xiaomi/hermes/proprietary/lib64/libperfservice.so:system/lib64/libperfservice.so \
    vendor/xiaomi/hermes/proprietary/lib64/libperfservicenative.so:system/lib64/libperfservicenative.so \
    vendor/xiaomi/hermes/proprietary/lib64/libpppbtdun.so:system/lib64/libpppbtdun.so \
    vendor/xiaomi/hermes/proprietary/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
    vendor/xiaomi/hermes/proprietary/lib64/libpq_prot.so:system/lib64/libpq_prot.so \
    vendor/xiaomi/hermes/proprietary/lib64/libPQDCjni.so:system/lib64/libPQDCjni.so \
    vendor/xiaomi/hermes/proprietary/lib64/libPQjni.so:system/lib64/libPQjni.so \
    vendor/xiaomi/hermes/proprietary/lib64/librilmtk.so:system/lib64/librilmtk.so \
    vendor/xiaomi/hermes/proprietary/lib64/librilmtkmd2.so:system/lib64/librilmtkmd2.so \
    vendor/xiaomi/hermes/proprietary/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    vendor/xiaomi/hermes/proprietary/lib64/libstagefright_memutil.so:system/lib64/libstagefright_memutil.so \
    vendor/xiaomi/hermes/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/xiaomi/hermes/proprietary/lib64/libSwJpgCodec.so:system/lib64/libSwJpgCodec.so \
    vendor/xiaomi/hermes/proprietary/lib64/libsysutils.so:system/lib64/libsysutils.so \
    vendor/xiaomi/hermes/proprietary/lib64/libterservice.so:system/lib64/libterservice.so \
    vendor/xiaomi/hermes/proprietary/lib64/libtinyxml.so:system/lib64/libtinyxml.so \
    vendor/xiaomi/hermes/proprietary/lib64/libtouchfilter.so:system/lib64/libtouchfilter.so \
    vendor/xiaomi/hermes/proprietary/lib64/libudf.so:system/lib64/libudf.so \
    vendor/xiaomi/hermes/proprietary/lib64/libui.so:system/lib64/libui.so \
    vendor/xiaomi/hermes/proprietary/lib64/libui_ext.so:system/lib64/libui_ext.so \
    vendor/xiaomi/hermes/proprietary/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
    vendor/xiaomi/hermes/proprietary/lib64/libwapi.so:system/lib64/libwapi.so \
    vendor/xiaomi/hermes/proprietary/lib64/libwebrtc_audio_preprocessing.so:system/lib64/libwebrtc_audio_preprocessing.so \
    vendor/xiaomi/hermes/proprietary/lib64/libwebviewchromium_loader.so:system/lib64/libwebviewchromium_loader.so \
    vendor/xiaomi/hermes/proprietary/lib64/libwebviewchromium_plat_support.so:system/lib64/libwebviewchromium_plat_support.so \
    vendor/xiaomi/hermes/proprietary/lib64/libwifitest.so:system/lib64/libwifitest.so \
    vendor/xiaomi/hermes/proprietary/lib64/libyasalgo.so:system/lib64/libyasalgo.so \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/ACCDET.kl:system/usr/keylayout/ACCDET.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_0079_Product_0011.kl:system/usr/keylayout/Vendor_0079_Product_0011.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c219.kl:system/usr/keylayout/Vendor_046d_Product_c219.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_0583_Product_2060.kl:system/usr/keylayout/Vendor_0583_Product_2060.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_0b05_Product_4500.kl:system/usr/keylayout/Vendor_0b05_Product_4500.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1038_Product_1412.kl:system/usr/keylayout/Vendor_1038_Product_1412.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_12bd_Product_d015.kl:system/usr/keylayout/Vendor_12bd_Product_d015.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1689_Product_fd00.kl:system/usr/keylayout/Vendor_1689_Product_fd00.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1689_Product_fd01.kl:system/usr/keylayout/Vendor_1689_Product_fd01.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1689_Product_fe00.kl:system/usr/keylayout/Vendor_1689_Product_fe00.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_18d1_Product_2c40.kl:system/usr/keylayout/Vendor_18d1_Product_2c40.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1949_Product_0401.kl:system/usr/keylayout/Vendor_1949_Product_0401.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1bad_Product_f016.kl:system/usr/keylayout/Vendor_1bad_Product_f016.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1bad_Product_f023.kl:system/usr/keylayout/Vendor_1bad_Product_f023.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1bad_Product_f027.kl:system/usr/keylayout/Vendor_1bad_Product_f027.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1bad_Product_f036.kl:system/usr/keylayout/Vendor_1bad_Product_f036.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_1d79_Product_0009.kl:system/usr/keylayout/Vendor_1d79_Product_0009.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_2378_Product_1008.kl:system/usr/keylayout/Vendor_2378_Product_1008.kl \
    vendor/xiaomi/hermes/proprietary/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl \
    vendor/xiaomi/hermes/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/xiaomi/hermes/proprietary/vendor/etc/diracmobile.config:system/vendor/etc/diracmobile.config \
    vendor/xiaomi/hermes/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/audio.a2dp.blueangel.so:system/vendor/lib/hw/audio.a2dp.blueangel.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/bluetooth.blueangel.so:system/vendor/lib/hw/bluetooth.blueangel.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/hw/gralloc.mt6795.so:system/vendor/lib/hw/gralloc.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libEGL_mtk.so:system/vendor/lib64/egl/libEGL_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libGLESv1_CM_mtk.so:system/vendor/lib64/egl/libGLESv1_CM_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/egl/libGLESv2_mtk.so:system/vendor/lib64/egl/libGLESv2_mtk.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/hw/gralloc.mt6795.so:system/vendor/lib64/hw/gralloc.mt6795.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcom_fingerprints_productiontestmanager.so:system/vendor/lib64/libcom_fingerprints_productiontestmanager.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libcom_fingerprints_sensor.so:system/vendor/lib64/libcom_fingerprints_sensor.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libglslcompiler.so:system/vendor/lib64/libglslcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libIMGegl.so:system/vendor/lib64/libIMGegl.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/liboclcompiler.so:system/vendor/lib64/liboclcompiler.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libprodtestlib.so:system/vendor/lib64/libprodtestlib.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libpvrANDROID_WSEGL.so:system/vendor/lib64/libpvrANDROID_WSEGL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libPVROCL.so:system/vendor/lib64/libPVROCL.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libPVRScopeServices.so:system/vendor/lib64/libPVRScopeServices.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libsrv_init.so:system/vendor/lib64/libsrv_init.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libsrv_um.so:system/vendor/lib64/libsrv_um.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libufwriter.so:system/vendor/lib64/libufwriter.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/libusc.so:system/vendor/lib64/libusc.so \
    vendor/xiaomi/hermes/proprietary/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so \
    vendor/xiaomi/hermes/proprietary/xbin/mnld:system/xbin/mnld
